### PR TITLE
fix BaseWrapper.withSigner() dichotomy

### LINKED ISSUE #68: The `BaseWrapper.withSigner()` dichotomy
Calling [withSigner](https://github.com/Fusyona/web3-core/blob/07945b41f2cd7f4b2e1fd7edd08e80ce4d3cb684/lib/base-wrapper.ts#L40) doesn't affect the result of [requireSigner()](https://github.com/Fusyona/web3-core/blob/main/lib/base-wrapper.ts#L18) and dependents. That's why [this test](https://github.com/Fusyona/launchpad-api/blob/aefc37a737a89c5b28dd9ff3c6a188bcd3ea1004/test/lbp-wrapper.test.ts#L71) is failing.

`withSigner()` is not needed in a dapp environment, since `requireSigner()` will always return the connected account. However, in a hardhat test environment the `requireSigner()` result is fixed (the first account in the list). Connecting a different account is desirable in some tests, that's why we should consider to allow the developer using our package to manually change the connected signer.

### PR DESCRIPTION
**Pull request by TheSnakeWitcher**
Close #68

### CODE REVIEW

**Review by adrianhdez929 — APPROVED** [review]
looks good to me

**Review by MakeMake23 — CHANGES_REQUESTED** [review]
Good approach @TheSnakeWitcher, thanks for proposing it. I think we need to add some tests before merging.

**Comment by TheSnakeWitcher** [comment]
My bad, I don't explain that before, just in case
- [ ] Now `connectSignerAndTransact()` holds the same logic that @MakeMake23 proposed, but don't connect the signer automatically, additionally now we return `transaction` and `receipt` for convenience 
- [ ] Now the `signer` isn't stored explicitly because it is managed by the `contract` that we wrap, these means that we can remove the `NoWallet` variant
- [ ] Note that I changed `waitAndReturn()` by `confirm` and now we return an object with both, the transaction and receipt. Rationale is to don't fetch the receipt twice

**Comment by adrianhdez929** [comment]
After your last comment I just have one question:
How its supposed to fix this the multi signers problem? We should create a single wrapper for each one? 
AFAIK, this was supposed to fix that issue

**Pull request merged**
